"""empty message

Revision ID: 6e8a60b143f8
Revises: 656bbb1d64d5
Create Date: 2021-04-04 19:02:10.423758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8a60b143f8'
down_revision = '656bbb1d64d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todo_comment_body', table_name='todo_comment')
    op.drop_table('todo_comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=100), nullable=False),
    sa.Column('todo_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['todo_id'], ['todo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_todo_comment_body', 'todo_comment', ['body'], unique=False)
    # ### end Alembic commands ###
